// Generated by gencpp from file test1/messages.msg
// DO NOT EDIT!


#ifndef TEST1_MESSAGE_MESSAGES_H
#define TEST1_MESSAGE_MESSAGES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace test1
{
template <class ContainerAllocator>
struct messages_
{
  typedef messages_<ContainerAllocator> Type;

  messages_()
    : name()
    , id(0)
    , fl(0.0)
    , points()
    , another_field(0)  {
    }
  messages_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , id(0)
    , fl(0.0)
    , points(_alloc)
    , another_field(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int64_t _id_type;
  _id_type id;

   typedef double _fl_type;
  _fl_type fl;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef uint8_t _another_field_type;
  _another_field_type another_field;





  typedef boost::shared_ptr< ::test1::messages_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test1::messages_<ContainerAllocator> const> ConstPtr;

}; // struct messages_

typedef ::test1::messages_<std::allocator<void> > messages;

typedef boost::shared_ptr< ::test1::messages > messagesPtr;
typedef boost::shared_ptr< ::test1::messages const> messagesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test1::messages_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test1::messages_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test1::messages_<ContainerAllocator1> & lhs, const ::test1::messages_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.id == rhs.id &&
    lhs.fl == rhs.fl &&
    lhs.points == rhs.points &&
    lhs.another_field == rhs.another_field;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test1::messages_<ContainerAllocator1> & lhs, const ::test1::messages_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test1::messages_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test1::messages_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test1::messages_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test1::messages_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::messages_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::messages_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test1::messages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f801381feac4b323373c99609c73f67";
  }

  static const char* value(const ::test1::messages_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f801381feac4b32ULL;
  static const uint64_t static_value2 = 0x3373c99609c73f67ULL;
};

template<class ContainerAllocator>
struct DataType< ::test1::messages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test1/messages";
  }

  static const char* value(const ::test1::messages_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test1::messages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int64 id\n"
"float64 fl\n"
"geometry_msgs/Point[] points\n"
"uint8 another_field\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::test1::messages_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test1::messages_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.id);
      stream.next(m.fl);
      stream.next(m.points);
      stream.next(m.another_field);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct messages_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test1::messages_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test1::messages_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "fl: ";
    Printer<double>::stream(s, indent + "  ", v.fl);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "another_field: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.another_field);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST1_MESSAGE_MESSAGES_H
