// Generated by gencpp from file test1/Sum.msg
// DO NOT EDIT!


#ifndef TEST1_MESSAGE_SUM_H
#define TEST1_MESSAGE_SUM_H

#include <ros/service_traits.h>


#include <test1/SumRequest.h>
#include <test1/SumResponse.h>


namespace test1
{

struct Sum
{

typedef SumRequest Request;
typedef SumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Sum
} // namespace test1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test1::Sum > {
  static const char* value()
  {
    return "713e5cf1444846805670f946f08bfc96";
  }

  static const char* value(const ::test1::Sum&) { return value(); }
};

template<>
struct DataType< ::test1::Sum > {
  static const char* value()
  {
    return "test1/Sum";
  }

  static const char* value(const ::test1::Sum&) { return value(); }
};


// service_traits::MD5Sum< ::test1::SumRequest> should match
// service_traits::MD5Sum< ::test1::Sum >
template<>
struct MD5Sum< ::test1::SumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test1::Sum >::value();
  }
  static const char* value(const ::test1::SumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test1::SumRequest> should match
// service_traits::DataType< ::test1::Sum >
template<>
struct DataType< ::test1::SumRequest>
{
  static const char* value()
  {
    return DataType< ::test1::Sum >::value();
  }
  static const char* value(const ::test1::SumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test1::SumResponse> should match
// service_traits::MD5Sum< ::test1::Sum >
template<>
struct MD5Sum< ::test1::SumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test1::Sum >::value();
  }
  static const char* value(const ::test1::SumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test1::SumResponse> should match
// service_traits::DataType< ::test1::Sum >
template<>
struct DataType< ::test1::SumResponse>
{
  static const char* value()
  {
    return DataType< ::test1::Sum >::value();
  }
  static const char* value(const ::test1::SumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST1_MESSAGE_SUM_H
