// Generated by gencpp from file test1/SumResponse.msg
// DO NOT EDIT!


#ifndef TEST1_MESSAGE_SUMRESPONSE_H
#define TEST1_MESSAGE_SUMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test1
{
template <class ContainerAllocator>
struct SumResponse_
{
  typedef SumResponse_<ContainerAllocator> Type;

  SumResponse_()
    : Sum(0)  {
    }
  SumResponse_(const ContainerAllocator& _alloc)
    : Sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _Sum_type;
  _Sum_type Sum;





  typedef boost::shared_ptr< ::test1::SumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test1::SumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SumResponse_

typedef ::test1::SumResponse_<std::allocator<void> > SumResponse;

typedef boost::shared_ptr< ::test1::SumResponse > SumResponsePtr;
typedef boost::shared_ptr< ::test1::SumResponse const> SumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test1::SumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test1::SumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test1::SumResponse_<ContainerAllocator1> & lhs, const ::test1::SumResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Sum == rhs.Sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test1::SumResponse_<ContainerAllocator1> & lhs, const ::test1::SumResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test1::SumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test1::SumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test1::SumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test1::SumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::SumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::SumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test1::SumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "055d509888d173367b1b9f94491341fd";
  }

  static const char* value(const ::test1::SumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x055d509888d17336ULL;
  static const uint64_t static_value2 = 0x7b1b9f94491341fdULL;
};

template<class ContainerAllocator>
struct DataType< ::test1::SumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test1/SumResponse";
  }

  static const char* value(const ::test1::SumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test1::SumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 Sum\n"
"\n"
;
  }

  static const char* value(const ::test1::SumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test1::SumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test1::SumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test1::SumResponse_<ContainerAllocator>& v)
  {
    s << indent << "Sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST1_MESSAGE_SUMRESPONSE_H
