// Generated by gencpp from file learning_tf/data.msg
// DO NOT EDIT!


#ifndef LEARNING_TF_MESSAGE_DATA_H
#define LEARNING_TF_MESSAGE_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_tf
{
template <class ContainerAllocator>
struct data_
{
  typedef data_<ContainerAllocator> Type;

  data_()
    : encl(0.0)  {
    }
  data_(const ContainerAllocator& _alloc)
    : encl(0.0)  {
  (void)_alloc;
    }



   typedef float _encl_type;
  _encl_type encl;





  typedef boost::shared_ptr< ::learning_tf::data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_tf::data_<ContainerAllocator> const> ConstPtr;

}; // struct data_

typedef ::learning_tf::data_<std::allocator<void> > data;

typedef boost::shared_ptr< ::learning_tf::data > dataPtr;
typedef boost::shared_ptr< ::learning_tf::data const> dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_tf::data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_tf::data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_tf::data_<ContainerAllocator1> & lhs, const ::learning_tf::data_<ContainerAllocator2> & rhs)
{
  return lhs.encl == rhs.encl;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_tf::data_<ContainerAllocator1> & lhs, const ::learning_tf::data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_tf

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::learning_tf::data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_tf::data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_tf::data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_tf::data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_tf::data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_tf::data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_tf::data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7df7554d5ca6fa53e385357d20f9e997";
  }

  static const char* value(const ::learning_tf::data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7df7554d5ca6fa53ULL;
  static const uint64_t static_value2 = 0xe385357d20f9e997ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_tf::data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_tf/data";
  }

  static const char* value(const ::learning_tf::data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_tf::data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 encl\n"
;
  }

  static const char* value(const ::learning_tf::data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_tf::data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.encl);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_tf::data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_tf::data_<ContainerAllocator>& v)
  {
    s << indent << "encl: ";
    Printer<float>::stream(s, indent + "  ", v.encl);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_TF_MESSAGE_DATA_H
